# Generated by Django 4.1.7 on 2023-02-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='run',
            name='dur',
            field=models.IntegerField(default=None),
        ),
    ]
