# Generated by Django 4.1.7 on 2023-02-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_run_category_run_distance_alter_run_dur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(default=None),
        ),
    ]
